# numpy

In [1]:
import numpy as np #anaconda

## 넘파이의 array메서드 인수로 시퀀스 자료형을 넣으면 ndarray 클래스 객체 -> 넘파이 배열로 변환

In [2]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 결과가 리스트와 같아 보이지만 다르다!

In [3]:
type(ar)

numpy.ndarray

### shape을 사용하면 넘파이 배열의 모양을 확인할 수 있다.

In [4]:
ar.shape

(10,)

In [5]:
ar2 = np.array([0.1,12,50,2,3.14])

In [6]:
#표현범위가 더 넓은 자료형으로 만듦
ar2

array([ 0.1 , 12.  , 50.  ,  2.  ,  3.14])

In [7]:
np.array([1,2,3]).dtype

dtype('int32')

### dtype = 'U'유니코드 string 더하면 문자열로 더해짐

In [8]:
x = np.array([1,2,3], dtype = 'U')
x[0] + x[1]

'12'

### 무한대를 표현하기 위해 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)가 있다.

In [9]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

C:\Users\user\AppData\Local\Temp\ipykernel_16912\1032392073.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
C:\Users\user\AppData\Local\Temp\ipykernel_16912\1032392073.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [10]:
np.log(0)

C:\Users\user\AppData\Local\Temp\ipykernel_16912\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [11]:
np.exp(-np.inf)

0.0

In [12]:
data = [0,1,2,3,4,5,6,7,8,9]

x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 넘파이 배열 객체의 벡터화 연산을 사용하면 간단하게 표현 가능 / 빠름

In [13]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
len(c)

2

In [16]:
len(c[0])

3

In [17]:
c.shape

(2, 3)

In [18]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
# 2 x 3 x 4
e = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [20]:
e.shape

(2, 2, 4)

In [21]:
len(e),len(e[0]),len(e[0][0])

(2, 2, 4)

#### 차원을 알아내는 ndim속성

In [22]:
print(e.ndim)

3


##### 일차원 배열의 리스트는 인덱싱과 같다

In [23]:
a = np.array([0,1,2,3,4])

In [24]:
a[2]

2

In [25]:
a[-1]

4

In [26]:
test = [[1,2,3,4],[5,6,7,8]]
test[1][1]

6

In [27]:
test = [[1,2,3,4],[5,6,7,8]]
test[0][:3]

[1, 2, 3]

#### 배열의 인덱싱

In [28]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
a[0,0]

0

In [30]:
a[0,1]

1

In [31]:
a[-1,-1]

5

### 슬라이싱

In [32]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:,2])
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


### numpy는 단순한 배열을 생성하는 명령을 제공한다.

In [33]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [34]:
a.dtype

dtype('float64')

##### "i" int로 바꿈 -> i8은 다 1로 초기화

In [35]:
a = np.zeros((5),dtype = "i") #int로 바꿈 -> i8은 다 1로 초기화
a

array([0, 0, 0, 0, 0], dtype=int32)

In [36]:
d = np.zeros(5,dtype = "U4") #-> U4 = uniqe 4(길이)
d

array(['', '', '', '', ''], dtype='<U4')

In [37]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [38]:
f = np.ones_like(d, dtype = "f")
f

array([1., 1., 1., 1., 1.], dtype=float32)

In [39]:
f = np.zeros_like(d, dtype = "f")
f

array([0., 0., 0., 0., 0.], dtype=float32)

##### empty는 기존에 메모리에 저장되어 있던 쓰레기 값으로 초기화 된다.

In [40]:
g = np.empty((4,3))
g

array([[1.17874116e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 1.08221785e-312, 1.16095484e-028],
       [3.74168445e+233, 3.10573437e-115, 1.69086561e+190],
       [6.48224637e+170, 3.67145870e+228, 1.73810553e-076]])

##### 배열 생성 arange명령은 특정 규칙에 따라 증가하는 수열

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

##### linspace / logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

In [43]:
ex = np.linspace(0,100,5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [44]:
ex2 = np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

#### .T 전치연산 (teanspose) 행과 열을 바꿈 (메서드가 아닌 속성)

In [45]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### reshape 배열의 크기 변형 (reshape)

In [47]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
b =  a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
#나누어 떨어지는 숫자로 해서 맞춰주어야 한다.
b =  a.reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### flatten / ravel 일차원으로 만듦

In [50]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### newaxis 새로운 차원을 증가시킨다

In [52]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### concatenate 행,열의 수가 같은 배열 연결

In [53]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

##### hstack 열의 수가 더 많은 배열을 생성(수평)

In [55]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

##### vstack 행의 수가 더 많은 배열을 생성(수직)

##### ones / zeros -> 1 / 0으로 초기화

In [56]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### dstack 깊이 수가 더 많은 배열을 생성

In [59]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [62]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

##### stack 명령 dstack기능을 확장한 것 -> 지정한 차원으로 배열 연결 (크기가 같아야한다)

In [63]:
c = np.stack([c1,c2],axis = 0)
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
c.shape

(2, 3, 4)

In [65]:
c = np.stack([c1,c2],axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [66]:
c.shape

(3, 2, 4)

In [67]:
d1 = np.ones((4,5))
d2 = np.zeros((4,5))
d3 = np.arange(20).reshape(4,5)

In [68]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
np.stack([d1,d2,d3], axis = 0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [72]:
np.stack([d1,d2,d3], axis = 1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [73]:
np.stack([d1,d2,d3], axis = 2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

#### r_[ ] 메서드는 특수 메서드 인덱서라고 한다.

#### c_[ ] 메서드는 colum단위로 차원을 증가시킨 후 좌우로 연결

#### tile 명령은 동일한 배열을 반복하여 연결

In [74]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
np.tile(a,(4,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [76]:
d1 = np.zeros((3,3))
d2 = np.ones((3,2))
d3 = np.arange(10,151,10).reshape(3,5)

In [77]:
h1 = np.hstack([d1,d2])

In [78]:
h2 = np.vstack([h1,d3])

In [79]:
np.tile(h2,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

#### AII 명령 -> 원소가 다 같은지 확인

#### ANY 명령 -> 원소가 하나라도 같은지 확인

In [80]:
np.all(a==b)

False

In [81]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [83]:
x = np.arange(12).reshape(3,4)

In [84]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드 캐스팅

### -> 모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환

#### 스칼라 기법 -> 스칼라를 벡터와 같은 크기로 확장시킨다
#### 확장 가능한 경우 (하나만 충족)
##### 1. 해당 차원 간의 숫자가 동일한 경우
##### 2. 해당 차원 중 하나가 1인 경우

In [85]:
a = np.array([1,2,3])
b = 2.0
a*b

array([2., 4., 6.])

## 차원 축소 연산

### 여러개의 차원을 연산하여 차원을 축소한다.

In [86]:
# 최대/ 최소 : min,max,argmin,argmax
# 통계 : sum, mean, median, std, var
# 불리언 : all, any

In [87]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
np.sum(x)

66

In [89]:
x.sum()

66

In [90]:
x.sum(axis=0) #세로로 계산( column)열 - 세로

array([12, 15, 18, 21])

In [91]:
x.sum(axis=1) #가로로 계산( row)행 - 가로

array([ 6, 22, 38])

### argmin( ) -> 해당 배열의 제일 작은 값의 인덱스 반환

In [92]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
x.argmin()

0

In [94]:
x.argmin(axis = 0)

array([0, 0, 0, 0], dtype=int64)

In [95]:
np.argmin(x,axis = 1)

array([0, 0, 0], dtype=int64)

In [96]:
import random

test = np.array([random.randint(1,99) for _ in range(20)]).reshape(2,5,-1)

In [97]:
test

array([[[93, 21],
        [39, 98],
        [34, 27],
        [79, 77],
        [91, 58]],

       [[14, 74],
        [77, 51],
        [44, 48],
        [61, 61],
        [23, 13]]])

In [98]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [99]:
((a <= b) & (b <= c )).all()

True

In [100]:
a = np.zeros((100, 100), dtype = np.int64)

In [101]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [102]:
np.any(a!=0) #하나도 0이 아니다

False

In [103]:
np.all(a==a)

True

In [104]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                    [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                    [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                    [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                    [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [105]:
practice.max() #전체의 최대값

9.0

In [106]:
practice.sum(axis = 1) # 행간의 합

array([32. , 30.7, 34.3, 24.7, 29.7])

In [107]:
practice.max(axis = 1) #행간의 최대값

array([8. , 9. , 8.9, 8.2, 8.9])

In [108]:
practice.mean(axis = 0) # 열간의 평균

array([4.02, 5.4 , 4.72, 5.2 , 5.64, 5.3 ])

In [109]:
practice.min(axis = 0) # 열간의 최소값

array([0.7, 1.1, 2.7, 2.1, 2.8, 0.2])

In [110]:
practice.max()
practice.sum(axis = 0)
practice.max(axis = 0)
practice.mean(axis = 1)
practice.min(axis = 1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 정렬

### numpy.sort() 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만든다.
### axis = 0 각각의 행을 따로 정렬하고  / axis = 1 각각의 열을 따로 정렬한다

In [111]:
a = np.array([random.randint(1,30) for _ in range(5)])

In [112]:
a

array([21,  2, 10,  9, 22])

In [113]:
j = np.argsort(a)

In [114]:
j #정렬 인덱스 값

array([1, 3, 2, 0, 4], dtype=int64)

In [115]:
a[j]

array([ 2,  9, 10, 21, 22])

In [116]:
np.sort(a)

array([ 2,  9, 10, 21, 22])

# 고급 인덱싱

In [117]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [119]:
print(a[0,0],a[1,1],a[2,0])

1 4 5


In [120]:
a[::-1 , [0,1,0]]

array([[5, 6, 5],
       [3, 4, 3],
       [1, 2, 1]])

In [121]:
a[: , [0,1,0]]

array([[1, 2, 1],
       [3, 4, 3],
       [5, 6, 5]])

In [122]:
scores = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])

In [123]:
scores[:,[2,1,3,0]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [124]:
j = np.argsort(scores[1])

In [125]:
scores[:,j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### 표본평균 - mean

In [126]:
np.mean(x)

5.5

### 표본 분산 - var

In [127]:
np.var(x)

11.916666666666666

### 표준편차 - std

In [128]:
np.std(x)

3.452052529534663

### 중앙값 - median

In [129]:
np.median(x)

5.5

### 시드 설정하기 - seed

In [130]:
np.random.rand(5)

array([0.00991384, 0.51752138, 0.4526404 , 0.76063141, 0.41075048])

In [131]:
np.random.seed(0)

In [132]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [133]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [134]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### shuffle - 데이터의 순서 바꾸기

In [135]:
np.random.rand(10) #1차원

array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ])

In [136]:
np.random.shuffle(x)
x

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

### choice함수  - 데이터 샘플링

In [166]:
np.random.choice(5,5,replace = False) #shuffle과 같다.

array([1, 2, 4, 0, 3])

In [170]:
np.random.choice(5,3,replace = False) #3개만 선택 반복x

array([4, 3, 2])

In [168]:
np.random.choice(5,10) #반복해서 10개 선택

array([4, 0, 2, 3, 3, 1, 3, 4, 3, 3])

In [169]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) #선택 확률 다르게 해서 10개 선택

array([0, 3, 2, 3, 0, 2, 0, 2, 3, 3])

### random 난수 생성 rand / randn / randint

In [141]:
np.random.rand(10) #1차원

array([0.28280696, 0.12019656, 0.2961402 , 0.11872772, 0.31798318,
       0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949])

In [142]:
np.random.rand(10) #1차원

array([0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895,
       0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136])

In [143]:
res = np.random.randint(2, size = 100)
res

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1])

In [144]:
result = res.mean()
result

0.5

In [145]:
np.random.seed(0)
coin_result = np.random.randint(0,2,100)
coin_result

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [146]:
coin_result.mean()

0.56

#### rand 확률 분포 실수 난수 생성 0~1사이

In [147]:
import numpy as np
np.random.rand(10)

array([0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559])

In [148]:
np.random.rand(3,5)

array([[0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236],
       [0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358]])

#### randn 기댓값 0 이고 표준편차가 1인 표준 정규 분포를 따르는 난수 생성 

In [149]:
np.random.randn(10)

array([-0.36433431, -0.67877739, -0.35362786, -0.74074747, -0.67502183,
       -0.13278426,  0.61980106,  1.79116846,  0.17100044, -1.72567135])

In [150]:
np.random.randn(3,5)

array([[ 0.16065854, -0.85898532, -0.20642094,  0.48842647, -0.83833097],
       [ 0.38116374, -0.99090328,  1.01788005,  0.3415874 , -1.25088622],
       [ 0.92525075, -0.90478616,  1.84369153,  1.52550724, -1.44553558]])

#### randint 함수는 np.random.randint(low, high=None, size=None)

In [151]:
np.random.randint(10, size=10)

array([0, 4, 3, 6, 9, 8, 0, 8, 5, 9])

In [152]:
np.random.randint(10,20,size=10)

array([10, 19, 16, 15, 13, 11, 18, 10, 14, 19])

In [153]:
np.random.randint(10,20,size=(3,5))

array([[16, 15, 17, 18, 18],
       [19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18]])

#### uniqe / bincount 정수 데이터 카운팅

In [154]:
np.unique([11,11,2,2,34,34]) #중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력

array([ 2, 11, 34])

In [155]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts = True) # return_counts = True 각 값의 데이터 갯수

In [156]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [157]:
count

array([2, 2, 1], dtype=int64)

In [158]:
np.bincount([1,1,2,2,2,3], minlength = 6)  #특정 범위 안의 수는 minlength 인수를 설정

array([0, 2, 3, 1, 0, 0], dtype=int64)

### np.eye(n) 정사각형으로 행렬

In [159]:
import numpy as np

In [160]:
np.eye(4,dtype = 'i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [161]:
a = np.ones((2,3,2))

In [162]:
a.astype("int")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])