In [1]:
import numpy as np

In [2]:
import random

In [3]:
np.random.rand(6)

array([0.54673995, 0.36629399, 0.32634857, 0.23420082, 0.69559366,
       0.92638759])

In [4]:
np.random.seed(0)

In [7]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([[7,8,9],[10,11,12]])

In [8]:
ar1+ar2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
np.arange(1,10) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
a1 = np.zeros((1,4))
a1

array([[0., 0., 0., 0.]])

In [15]:
a2 = np.ones((1,1))
a2

array([[1.]])

In [16]:
a3 = np.zeros((1,5))
a3

array([[0., 0., 0., 0., 0.]])

In [17]:
np.hstack([a1,a2,a3])

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.arange(50)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [24]:

d = np.zeros((3,3,3),dtype = "U10") #-> U4 = uniqe 4(길이)
d

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [26]:

d = np.array(('playdata')) #-> U4 = uniqe 4(길이)
d

array('playdata', dtype='<U8')

In [34]:
h1 = np.hstack([d,d,d])
v1 = np.vstack([h1,h1,h1])
d1 = np.dstack([v1,v1,v1])
d1

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [35]:
np.full((3,3,3), ' ',dtype = "U10")

array([[[' ', ' ', ' '],
        [' ', ' ', ' '],
        [' ', ' ', ' ']],

       [[' ', ' ', ' '],
        [' ', ' ', ' '],
        [' ', ' ', ' ']],

       [[' ', ' ', ' '],
        [' ', ' ', ' '],
        [' ', ' ', ' ']]], dtype='<U10')

In [41]:
ar1 = np.arange(1,21)
ar = ar1 * 2
ar.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [52]:
r = np.random.rand(10)
np.random.seed(0)
r = np.random.rand(10)
np.array(r * 10,dtype='i')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [55]:
m = np.ones((10,10))

In [65]:
m[1:-1,1:-1] = 0
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [72]:
m = np.ones((10,10))

In [76]:
m[0,:] = 0
m[-1,:] = 0
m[:,0] = 0
m[:,-1] = 0
print(m)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [77]:
z = np.ones((10,10))
z[:,[0,-1]] = 0
z[[0,-1],:] = 0
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [131]:
z = np.ones((8,8))
z[[0,2,4,6],[1,3,5,7]] = 0
z

array([[1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [127]:
z = np.ones((8,8))
z[1::2,::2] = 0
z[::2,1::2] = 0
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [128]:
z = np.ones((8,8))
z[1::2,::2] = 0
#z[::2,1::2] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [145]:
ah = np.hstack([a,a,a,a])

In [146]:
np.vstack([ah,ah,ah,ah])

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]], dtype=float32)

In [144]:
a = np.array([[1,0],[0,1]],dtype = 'f')
ah = np.hstack([a,a,a,a])
np.vstack([ah,ah,ah,ah])

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]], dtype=float32)

In [148]:
np.tile(np.eye(2), (4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [149]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [151]:
even = np.array([True if i%2==0 else False for i in range(1,5)])
even

array([False,  True, False,  True])

In [152]:
a[even]

array([2, 4])

In [158]:
a = np.arange(10)
even = np.array([-i if 3<i<7 else i for i in range(11)])
even

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [163]:
a = np.arange(11)
a[(3<a) & (7>a)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [166]:
a = np.arange(3,100,3)
sum(a)

1683

In [191]:
ex = np.linspace(0.1,0.9,9)

In [192]:
ex

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [194]:
numbers = np.random.randint(1,45,6)
numbers

array([26, 14,  9, 10, 21, 17])

In [217]:
while True :
    try:
        num = int(input("갯수"))
        arr = np.arange(1,45)
        number = [np.sort(np.random.choice(arr,6,replace=False)) for _ in range(num)]
        print(number)
        break
    except :
        print("자연수만 입력해주세요.")

갯수 3


[array([ 6, 15, 17, 22, 30, 38]), array([ 4,  8, 20, 23, 24, 42]), array([ 3, 12, 15, 22, 31, 35])]


In [218]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])

In [234]:
(resp_time > 200).sum()

8

In [235]:
np.percentile(resp_time,25)

71.5

In [236]:
np.percentile(resp_time,50)

131.0

In [237]:
np.percentile(resp_time,75)

175.5

In [238]:
np.percentile(resp_time,100)

218.0

In [251]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

In [252]:
bin = np.bincount(result)
bins = np.argsort(bin)
print(p[bins[-1]],"가 ",bin[bins[-1]],"표로 반장으로 선출되었습니다.")

뽀로로 가  81 표로 반장으로 선출되었습니다.


In [257]:
count = np.bincount(result,minlength=3)
winner_index = count.argmax()
print(f'{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출 되었습니다.')

뽀로로가 81표로 반장으로 선출 되었습니다.
